export type Campus = {
  name: string;
  address: string;
  city: string;
  phone?: string;
};

export type School = {
  id: string; name: string; ktPlan?: string; city: string; state: string;
  type: string; gender: string; levels: string; orientation: string;
  transport: boolean; boarding: boolean; rating: number; reviews: number;
  verified: boolean; feeFrom: number; feeTo: number; color: string;
  tagline: string; features: string[]; scholarships: number; vacancies: number;
  students: string; established: number; address: string; phone: string;
  email: string; special?: boolean; specialFocus?: string[];
  campuses?: Campus[];
  bannerUrl?: string;
  imageUrl?: string;
  facilityImages?: Record<string, string[]>;
};

// Shared facility image pools by category
const FI = {
  scienceLab:  ['/schools/facility-schence-lab1.jpeg', '/schools/facility-sciencelab2.png', '/schools/facility-sciencelab3.webp'],
  computerLab: ['/schools/facility-computer-lab.jpg', '/schools/facility-computer-lab2.jpg', '/schools/facility-computer-lab3.jpg'],
  library:     ['/schools/facility-library.jpg', '/schools/facility-library2.jpg', '/schools/facility-library3.jpg'],
  sports:      ['/schools/extracurricular-sport.jpg', '/schools/extracurricular-sport2.jpg', '/schools/extracurricular-sport3.png', '/schools/extracurricular-sport4.jpg'],
  transport:   ['/schools/facility-schoolbus.jpg'],
  swimming:    ['/schools/facility-swimingpool.jpg'],
  nursery:     ['/schools/facility-nursery-playground.jpg', '/schools/bannery-nurseryschool.jpg', '/schools/banner-nurseryschool2.jpg', '/schools/banner-nurseryschool3.jpg'],
  hygiene:     ['/schools/facility-toilets.jpeg'],
  hostel:      ['/schools/facility-hostel.jpeg', '/schools/facility-hostel2.jpg'],
  music:       ['/schools/facility-music-lab.jpg', '/schools/extracurricular-band.jpg'],
  ict:         ['/schools/extra-curricular-ict.jpg', '/schools/facility-computer-lab2.jpg'],
  academic:    ['/schools/academic-session.jpg', '/schools/acedemic-session2.jpg', '/schools/academic-session3.jpg', '/schools/academic-session4.jpg'],
  life:        ['/schools/school-life-student-bonding.jpg', '/schools/handson.jpg', '/schools/extracurricular-seminar.jpg'],
  cultural:    ['/schools/extracuricular-cultural.jpg'],
  religion:    ['/schools/extracurricular-religion.jpg'],
  birthday:    ['/schools/extra-curricular-birthday.jpg'],
  club:        ['/schools/extracurricular-club1.jpg', '/schools/extracurricular-club2.jpg', '/schools/extracurricular-club3.jpg'],
};

export const SN_SCHOOLS: School[] = [
  {
    id:'gf', name:'Greenfield International School', ktPlan:'Premium',
    city:'Gwarinpa, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Christian', transport:true, boarding:false, rating:4.8, reviews:127, verified:true,
    feeFrom:380000, feeTo:780000, color:'#1A3D2C', tagline:'Excellence in Education',
    features:['Science Lab','Computer Lab','Sports Ground','Transport','Library','Sick Bay'],
    scholarships:4, vacancies:2, students:'600+', established:2007,
    address:'Plot 12, Gwarinpa Estate, Abuja', phone:'+234 803 441 0001', email:'info@greenfield.edu.ng',
    bannerUrl:'/schools/banner1.png',
    imageUrl:'/schools/banner1.png',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Transport': FI.transport,
      'Sick Bay': FI.academic,
    },
    campuses:[
      { name:'Gwarinpa Campus', address:'Plot 12, Gwarinpa Estate, Abuja', city:'Gwarinpa, Abuja', phone:'+234 803 441 0001' },
      { name:'Wuse II Campus',  address:'No. 5 Wole Soyinka Street, Wuse II, Abuja', city:'Wuse II, Abuja', phone:'+234 803 441 0002' },
      { name:'Kado Campus',     address:'Block B, Kado Estate, Kado, Abuja', city:'Kado, Abuja', phone:'+234 803 441 0003' },
    ],
  },
  {
    id:'hc', name:'Heritage College', ktPlan:'Standard',
    city:'Jabi, Abuja', state:'FCT', type:'Day & Boarding', gender:'Mixed', levels:'JSS–SSS',
    orientation:'Christian', transport:true, boarding:true, rating:4.7, reviews:212, verified:true,
    feeFrom:520000, feeTo:820000, color:'#2A6FDB', tagline:'Where Character Meets Excellence',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Chapel'],
    scholarships:3, vacancies:1, students:'800+', established:2003,
    address:'7 Jabi Lake Road, Jabi, Abuja', phone:'+234 805 987 6543', email:'info@heritagecollege.edu.ng',
    bannerUrl:'/schools/banner2.jpg',
    imageUrl:'/schools/banner2.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Boarding House': FI.hostel,
      'Chapel': FI.religion,
    },
  },
  {
    id:'sa', name:'Sunrise Academy', ktPlan:'Standard',
    city:'Garki, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.5, reviews:89, verified:true,
    feeFrom:420000, feeTo:680000, color:'#B87D20', tagline:"Raising Tomorrow's Leaders",
    features:['Computer Lab','Library','Sports Ground','Transport'],
    scholarships:1, vacancies:0, students:'450+', established:2011,
    address:'15 Aminu Kano Crescent, Garki II, Abuja', phone:'+234 802 123 4567', email:'info@sunriseacademy.edu.ng',
    bannerUrl:'/schools/banner3.jpg',
    imageUrl:'/schools/banner3.jpg',
    facilityImages:{
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Transport': FI.transport,
    },
    campuses:[
      { name:'Garki Campus',   address:'15 Aminu Kano Crescent, Garki II, Abuja', city:'Garki, Abuja', phone:'+234 802 123 4567' },
      { name:'Maitama Campus', address:'22 Panama Street, Maitama, Abuja', city:'Maitama, Abuja', phone:'+234 802 123 4568' },
    ],
  },
  {
    id:'ms', name:'Model Schools FCT',
    city:'Maitama, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Multi-faith', transport:false, boarding:false, rating:4.3, reviews:156, verified:true,
    feeFrom:350000, feeTo:620000, color:'#1F8A5B', tagline:'Academic Excellence, Moral Values',
    features:['Science Lab','Library','Sports Ground'],
    scholarships:0, vacancies:3, students:'750+', established:1998,
    address:'23 Aguiyi-Ironsi Street, Maitama, Abuja', phone:'+234 809 456 7890', email:'info@modelschools.edu.ng',
    bannerUrl:'/schools/banner4.png',
    imageUrl:'/schools/banner4.png',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
    },
  },
  {
    id:'rb', name:'Rainbow Nursery & Primary',
    city:'Wuse II, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Nursery–Primary',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.6, reviews:74, verified:true,
    feeFrom:280000, feeTo:480000, color:'#D4591A', tagline:'Every Child Counts',
    features:['Computer Lab','Library','Playground','Transport'],
    scholarships:0, vacancies:1, students:'300+', established:2014,
    address:'8 Amaechi Street, Wuse II, Abuja', phone:'+234 803 234 5678', email:'info@rainbownursery.edu.ng',
    bannerUrl:'/schools/bannery-nurseryschool.jpg',
    imageUrl:'/schools/bannery-nurseryschool.jpg',
    facilityImages:{
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Playground': FI.nursery,
      'Transport': FI.transport,
    },
  },
  {
    id:'cv', name:'Covenant Academy',
    city:'Lugbe, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Christian', transport:true, boarding:false, rating:4.4, reviews:98, verified:true,
    feeFrom:320000, feeTo:640000, color:'#7C3AED', tagline:'Faith, Knowledge, Excellence',
    features:['Science Lab','Library','Sports Ground','Transport'],
    scholarships:1, vacancies:2, students:'500+', established:2009,
    address:'Block C, Lugbe Extension, Abuja', phone:'+234 807 345 6789', email:'info@covenantacademy.edu.ng',
    bannerUrl:'/schools/banner5.jpg',
    imageUrl:'/schools/banner5.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Transport': FI.transport,
    },
  },
  {
    id:'li', name:'Lagos International School', ktPlan:'Premium',
    city:'Victoria Island', state:'Lagos', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Non-denominational', transport:false, boarding:false, rating:4.9, reviews:341, verified:true,
    feeFrom:680000, feeTo:1400000, color:'#C41E3A', tagline:'International Standards, Local Excellence',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Swimming Pool','Cafeteria'],
    scholarships:4, vacancies:5, students:'1,200+', established:1995,
    address:'14 Adeola Odeku Street, Victoria Island, Lagos', phone:'+234 812 456 7890', email:'info@lagosintl.edu.ng',
    bannerUrl:'/schools/banner6.png',
    imageUrl:'/schools/banner6.png',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Swimming Pool': FI.swimming,
      'Cafeteria': FI.life,
    },
    campuses:[
      { name:'Victoria Island Campus', address:'14 Adeola Odeku Street, Victoria Island, Lagos', city:'Victoria Island, Lagos', phone:'+234 812 456 7890' },
      { name:'Lekki Campus',           address:'Plot 45, Freedom Way, Lekki Phase 1, Lagos',     city:'Lekki, Lagos',            phone:'+234 812 456 7891' },
      { name:'Abuja Campus',           address:'No. 3 Udi Hills Street, Asokoro, Abuja',         city:'Asokoro, Abuja',          phone:'+234 812 456 7892' },
    ],
  },
  {
    id:'hil', name:'Hillcrest School', ktPlan:'Premium',
    city:'Jos, Plateau', state:'Plateau', type:'Day & Boarding', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Christian', transport:false, boarding:true, rating:4.6, reviews:188, verified:true,
    feeFrom:480000, feeTo:760000, color:'#0D9D8A', tagline:'Nurturing Global Citizens',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Chapel'],
    scholarships:2, vacancies:1, students:'700+', established:1962,
    address:'Hillcrest Road, Jos South, Plateau State', phone:'+234 808 567 8901', email:'info@hillcrest.edu.ng',
    bannerUrl:'/schools/banner7.jpg',
    imageUrl:'/schools/banner7.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Boarding House': FI.hostel,
      'Chapel': FI.religion,
    },
  },
  {
    id:'ka', name:"King's College Lagos",
    city:'Lagos Island', state:'Lagos', type:'Boarding', gender:'Boys', levels:'JSS–SSS',
    orientation:'Non-denominational', transport:false, boarding:true, rating:4.7, reviews:294, verified:true,
    feeFrom:350000, feeTo:650000, color:'#1E3A5F', tagline:'Tradition of Excellence Since 1909',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Music Room'],
    scholarships:3, vacancies:2, students:'1,100+', established:1909,
    address:'6 Kings College Road, Lagos Island, Lagos', phone:'+234 813 456 7891', email:'info@kingscollegelagos.edu.ng',
    bannerUrl:'/schools/banner9-all-boys-school.jpg',
    imageUrl:'/schools/banner9-all-boys-school.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Boarding House': FI.hostel,
      'Music Room': FI.music,
    },
  },
  {
    id:'qc', name:'Federal Government College Enugu',
    city:'Enugu, Enugu', state:'Enugu', type:'Boarding', gender:'Mixed', levels:'JSS–SSS',
    orientation:'Non-denominational', transport:false, boarding:true, rating:4.6, reviews:267, verified:true,
    feeFrom:320000, feeTo:580000, color:'#166534', tagline:'Excellence Through Federal Standards',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Music Room'],
    scholarships:2, vacancies:3, students:'1,000+', established:1960,
    address:'Independence Layout, Enugu, Enugu State', phone:'+234 802 567 8912', email:'info@fgcenugu.edu.ng',
    bannerUrl:'/schools/banner10.jpg',
    imageUrl:'/schools/banner10.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Boarding House': FI.hostel,
      'Music Room': FI.music,
    },
  },
  {
    id:'bca', name:'Bingham Academy',
    city:'Karu, Abuja', state:'FCT', type:'Day & Boarding', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Christian', transport:true, boarding:true, rating:4.5, reviews:143, verified:true,
    feeFrom:440000, feeTo:720000, color:'#7A4A00', tagline:'Excellence with Faith',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Chapel','Swimming Pool'],
    scholarships:2, vacancies:4, students:'650+', established:1978,
    address:'Karu-Mararaba Road, Karu, Abuja', phone:'+234 806 789 0123', email:'info@binghamacademy.edu.ng',
    bannerUrl:'/schools/banner12.jpg',
    imageUrl:'/schools/banner12.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Boarding House': FI.hostel,
      'Swimming Pool': FI.swimming,
    },
  },
  {
    id:'ld', name:'Ladela Schools', ktPlan:'Standard',
    city:'Surulere, Lagos', state:'Lagos', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Christian', transport:true, boarding:false, rating:4.5, reviews:0, verified:false,
    feeFrom:380000, feeTo:720000, color:'#065F46', tagline:'Grooming Leaders of Tomorrow',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport','Music Room'],
    scholarships:1, vacancies:2, students:'550+', established:2006,
    address:'14 Adeniran Ogunsanya Street, Surulere, Lagos', phone:'+234 807 890 1234', email:'info@ladelaschools.edu.ng',
    bannerUrl:'/schools/banner11.jpg',
    imageUrl:'/schools/banner11.jpg',
    facilityImages:{
      'Science Lab': FI.scienceLab,
      'Computer Lab': FI.computerLab,
      'Library': FI.library,
      'Sports Ground': FI.sports,
      'Transport': FI.transport,
      'Music Room': FI.music,
    },
  },
  {
    id:'dov', name:'Dovenest Secondary School', ktPlan:'Standard',
    city:'Wuse, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'JSS–SSS',
    orientation:'Christian', transport:true, boarding:false, rating:4.6, reviews:134, verified:true,
    feeFrom:400000, feeTo:720000, color:'#1A4D6E', tagline:'Nurturing Excellence, Building Character',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport','Music Room'],
    scholarships:2, vacancies:2, students:'520+', established:2004,
    address:'Plot 1181, Cadastral Zone, Wuse 2, Abuja', phone:'+234 805 901 2345', email:'info@dovenest.edu.ng',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Transport':FI.transport, 'Music Room':FI.music },
  },
  {
    id:'pac', name:'Pacelli School for the Blind',
    city:'Surulere, Lagos', state:'Lagos', type:'Day & Boarding', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Christian', transport:true, boarding:true, rating:4.7, reviews:64, verified:true,
    feeFrom:320000, feeTo:580000, color:'#6B3FA0', tagline:'Empowering the Visually Impaired',
    features:['Braille Library','Mobility Training','Music Room','Boarding House','Medical Unit'],
    scholarships:3, vacancies:1, students:'220+', established:1975,
    address:'Surulere, Lagos', phone:'+234 801 234 5670', email:'info@pacelli.edu.ng',
    special:true, specialFocus:['Visual impairment','Low vision'],
    bannerUrl:'/schools/banner14.jpg',
    imageUrl:'/schools/banner14.jpg',
    facilityImages:{
      'Boarding House': FI.hostel,
      'Music Room': FI.music,
    },
  },
  {
    id:'sfd', name:'FCT School for the Deaf',
    city:'Karu, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.5, reviews:41, verified:true,
    feeFrom:280000, feeTo:500000, color:'#2A6FDB', tagline:'Communication Without Barriers',
    features:['Sign Language Studio','Computer Lab','Sports Ground','Transport','Speech Therapy'],
    scholarships:2, vacancies:2, students:'180+', established:1989,
    address:'Karu District, Abuja', phone:'+234 802 345 6781', email:'info@fctdeafschool.edu.ng',
    special:true, specialFocus:['Hearing impairment','Speech & language'],
    bannerUrl:'/schools/banner15.jpg',
    imageUrl:'/schools/banner15.jpg',
    facilityImages:{
      'Computer Lab': FI.computerLab,
      'Sports Ground': FI.sports,
      'Transport': FI.transport,
    },
  },
  {
    id:'sts', name:'Stepping Stones Special School',
    city:'Ikeja, Lagos', state:'Lagos', type:'Day', gender:'Mixed', levels:'Nursery–Primary',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.8, reviews:88, verified:true,
    feeFrom:380000, feeTo:620000, color:'#D97757', tagline:'Every Child Can Learn',
    features:['Therapy Rooms','Sensory Room','Computer Lab','Transport','Small Class Sizes'],
    scholarships:1, vacancies:1, students:'120+', established:2005,
    address:'Ikeja, Lagos', phone:'+234 803 456 7892', email:'info@steppingstones.edu.ng',
    special:true, specialFocus:['Dyslexia','Dyscalculia','ADHD','Autism','Cerebral Palsy'],
    bannerUrl:'/schools/banner16.jpg',
    imageUrl:'/schools/banner16.jpg',
    facilityImages:{
      'Computer Lab': FI.computerLab,
      'Transport': FI.transport,
    },
  },
  {
    id:'fe', name:'Federal Government College Enugu',
    city:'Enugu', state:'Enugu', type:'Boarding', gender:'Mixed', levels:'JSS–SSS',
    orientation:'Non-denominational', transport:false, boarding:true, rating:4.4, reviews:183, verified:true,
    feeFrom:280000, feeTo:520000, color:'#166534', tagline:'Federal Standards, National Pride',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House'],
    scholarships:2, vacancies:3, students:'900+', established:1973,
    address:'Iva Valley Road, Enugu, Enugu State', phone:'+234 814 567 8901', email:'info@fgcenugu.edu.ng',
    bannerUrl:'/schools/banner17.jpg', imageUrl:'/schools/banner17.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Boarding House':FI.hostel },
  },
  {
    id:'gra', name:'GRA International School Port Harcourt', ktPlan:'Standard',
    city:'GRA, Port Harcourt', state:'Rivers', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.5, reviews:112, verified:true,
    feeFrom:420000, feeTo:780000, color:'#7E1D1D', tagline:'Excellence in the Oil City',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport','Swimming Pool'],
    scholarships:2, vacancies:2, students:'550+', established:2001,
    address:'GRA Phase 2, Port Harcourt, Rivers State', phone:'+234 806 678 9012', email:'info@graintl.edu.ng',
    bannerUrl:'/schools/banner18.jpg', imageUrl:'/schools/banner18.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Transport':FI.transport, 'Swimming Pool':FI.swimming },
  },
  {
    id:'eko', name:'Eko International School', ktPlan:'Premium',
    city:'Lekki, Lagos', state:'Lagos', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.7, reviews:198, verified:true,
    feeFrom:580000, feeTo:1100000, color:'#B45309', tagline:'Where Global Meets Local',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport','Swimming Pool','Music Room'],
    scholarships:3, vacancies:3, students:'680+', established:2003,
    address:'Plot 14 Admiralty Way, Lekki Phase 1, Lagos', phone:'+234 807 789 0123', email:'info@ekointl.edu.ng',
    bannerUrl:'/schools/banner-19.jpg', imageUrl:'/schools/banner-19.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Transport':FI.transport, 'Swimming Pool':FI.swimming, 'Music Room':FI.music },
  },
  {
    id:'nav', name:'Naval Secondary School Lagos',
    city:'Ojo, Lagos', state:'Lagos', type:'Day & Boarding', gender:'Mixed', levels:'JSS–SSS',
    orientation:'Non-denominational', transport:false, boarding:true, rating:4.6, reviews:229, verified:true,
    feeFrom:300000, feeTo:560000, color:'#1E3A5F', tagline:'Discipline, Diligence, Distinction',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House'],
    scholarships:1, vacancies:1, students:'800+', established:1983,
    address:'Naval Base, Ojo, Lagos State', phone:'+234 808 890 1234', email:'info@navalsecondary.edu.ng',
    bannerUrl:'/schools/banner-20.jpg', imageUrl:'/schools/banner-20.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Boarding House':FI.hostel },
  },
  {
    id:'ath', name:'Athenian Academy Abuja', ktPlan:'Standard',
    city:'Apo, Abuja', state:'FCT', type:'Day', gender:'Mixed', levels:'Primary–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.5, reviews:91, verified:true,
    feeFrom:390000, feeTo:690000, color:'#3730A3', tagline:'Knowledge Without Limits',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport','Music Room'],
    scholarships:2, vacancies:3, students:'480+', established:2013,
    address:'Apo Legislative Quarters Road, Abuja', phone:'+234 809 901 2345', email:'info@athenianacademy.edu.ng',
    bannerUrl:'/schools/banner-21.jpg', imageUrl:'/schools/banner-21.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Transport':FI.transport, 'Music Room':FI.music },
  },
  {
    id:'bri', name:'Brilliant Minds International School',
    city:'Ikeja, Lagos', state:'Lagos', type:'Day', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Non-denominational', transport:true, boarding:false, rating:4.4, reviews:78, verified:true,
    feeFrom:360000, feeTo:660000, color:'#0F766E', tagline:'Shaping Brilliant Futures',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Transport'],
    scholarships:1, vacancies:2, students:'430+', established:2010,
    address:'Allen Avenue, Ikeja, Lagos State', phone:'+234 810 012 3456', email:'info@brilliantminds.edu.ng',
    bannerUrl:'/schools/banner22.jpg', imageUrl:'/schools/banner22.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Transport':FI.transport },
  },
  {
    id:'vic', name:'Victory Heights Academy', ktPlan:'Standard',
    city:'Ibadan', state:'Oyo', type:'Day & Boarding', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Christian', transport:true, boarding:true, rating:4.5, reviews:104, verified:true,
    feeFrom:340000, feeTo:620000, color:'#6D28D9', tagline:'Rising Higher Every Day',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Transport'],
    scholarships:2, vacancies:4, students:'520+', established:2006,
    address:'Bodija Estate, Ibadan, Oyo State', phone:'+234 811 123 4567', email:'info@victoryheights.edu.ng',
    bannerUrl:'/schools/banner23.jpg', imageUrl:'/schools/banner23.jpg',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Boarding House':FI.hostel, 'Transport':FI.transport },
  },
  {
    id:'cre', name:'Crescent International School', ktPlan:'Premium',
    city:'Kano', state:'Kano', type:'Day & Boarding', gender:'Mixed', levels:'Nursery–SSS',
    orientation:'Multi-faith', transport:true, boarding:true, rating:4.6, reviews:158, verified:true,
    feeFrom:380000, feeTo:720000, color:'#0C4A6E', tagline:'Crescent of Knowledge, Circle of Excellence',
    features:['Science Lab','Computer Lab','Library','Sports Ground','Boarding House','Swimming Pool','Transport'],
    scholarships:3, vacancies:2, students:'600+', established:1999,
    address:'Nassarawa GRA, Kano, Kano State', phone:'+234 812 234 5678', email:'info@crescentintl.edu.ng',
    bannerUrl:'/schools/banner8.png', imageUrl:'/schools/banner8.png',
    facilityImages:{ 'Science Lab':FI.scienceLab, 'Computer Lab':FI.computerLab, 'Library':FI.library, 'Sports Ground':FI.sports, 'Boarding House':FI.hostel, 'Swimming Pool':FI.swimming, 'Transport':FI.transport },
  },
];

export const FEATURED_IDS = ['gf','li','hc','ka','hil','bca','cre','gra','sa','qc','nav','fe','ath','vic','eko'];
export const CAROUSEL     = SN_SCHOOLS.filter(s => FEATURED_IDS.includes(s.id));
export const HIGHLY_RATED = [...SN_SCHOOLS].filter(s => !s.special).sort((a,b) => b.rating - a.rating).slice(0,6);

export const MOCK_REVIEWS = [
  { name:'Mrs A. O.', rating:5, date:'May 2026', text:'Excellent school! My children have thrived here. The teachers are dedicated and communication with parents is superb.', tag:'Academic quality' },
  { name:'Mr T. F.',  rating:4, date:'Apr 2026', text:'Very good school overall. The bus service is reliable and the staff are responsive. The science lab impressed me the most.', tag:'Transport & safety' },
  { name:'Mrs Z. S.', rating:5, date:'Mar 2026', text:'My daughter has grown so much academically and in character. The teachers really care. Highly recommended.', tag:'Character development' },
  { name:'Mr E. N.',  rating:4, date:'Feb 2026', text:'Fees are reasonable for the quality of education. I wish there were more extracurricular activities but the core academics are excellent.', tag:'Value for money' },
  { name:'Mrs C. A.', rating:5, date:'Jan 2026', text:'Safe environment, great facilities, wonderful teachers. My son loves going to school every day. The PTA is also very active.', tag:'School environment' },
  { name:'Mr D. O.',  rating:3, date:'Dec 2025', text:'Good school but the dining food could be better. Teachers are hardworking and results are consistently strong.', tag:'Facilities' },
];

export const SN_PARENT_FEATURES = [
  { emoji:'📊', title:'Results, instantly', text:'CA scores, exams, class standing, and term report cards — on your phone the moment they are published. No printing. No waiting.' },
  { emoji:'💬', title:'School communication that works', text:"Targeted announcements for your child's class. Absence notes in two taps. No WhatsApp groups. No lost messages." },
  { emoji:'📅', title:'Attendance and calendar', text:'See every day your child was present, absent, or excused. School events, PTA dates, and exam schedules in one calendar.' },
  { emoji:'💳', title:'Fee payments and receipts', text:'Pay full or part from your phone. Siblings combined. Instant receipts. Complete payment history.' },
  { emoji:'🔔', title:'Pickup confirmation', text:'Every pickup verified with a 4-digit code. Medical alerts visible to the driver at handover.' },
  { emoji:'🚌', title:'Live bus tracking', text:'See the bus on a map. Get notified when your child boards and when they arrive — for families on the school bus.' },
];

export type Vacancy = {
  id: string; sId: string; sName: string; sColor: string; city: string; state: string;
  title: string; dept: string; type: string; deadline: string; summary: string; applyEmail: string;
  // Extended fields from 0032 + 0033 migrations
  roleOverview: string | null;
  keyResponsibilities: string | null;
  requirements: string | null;
  perks: string[];
  salaryRange: string | null;
  minQualification: string | null;
  experienceLevel: string | null;
  location: string | null;
  trcnRequired: boolean;
  applyInstructions: string | null;
};

export const SN_VACANCIES: Vacancy[] = [
  {
    id:'v1', sId:'gf', sName:'Greenfield International School', sColor:'#1A3D2C',
    city:'Gwarinpa, Abuja', state:'FCT', dept:'Secondary – Academic', type:'Full-time',
    title:'Mathematics Teacher (SSS)', deadline:'30 Jul 2026',
    summary:'TRCN-registered Maths teacher for SSS 1–3. Strong classroom management and a proven WAEC results record required.',
    applyEmail:'careers@greenfield.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (3–7 years)', minQualification: 'B.Sc. / B.Ed.',
    salaryRange: '₦80k–₦120k/month', location: 'Gwarinpa, Abuja',
    roleOverview: 'Greenfield International School is seeking a dedicated, results-driven Mathematics Teacher to deliver high-quality instruction to our Senior Secondary students (SSS 1–3). You will foster deep understanding of mathematical concepts, prepare students comprehensively for WAEC and NECO, and contribute to our tradition of outstanding academic results. The ideal candidate brings both subject mastery and genuine passion for inspiring young mathematicians.',
    keyResponsibilities: 'Plan and deliver engaging, differentiated Mathematics lessons for SSS 1, 2, and 3\nPrepare students thoroughly for WAEC, NECO, and UTME Mathematics papers\nSet, mark, and return assignments, tests, and terminal examinations promptly\nTrack individual student performance and provide targeted intervention for struggling learners\nMaintain accurate records of student progress and submit timely termly reports\nCollaborate with the Head of Department on scheme of work and curriculum planning\nParticipate in parents\' evenings, staff development days, and school events\nSupervise after-school Mathematics prep and revision sessions',
    requirements: 'B.Sc. or B.Ed. in Mathematics or Mathematics Education (minimum second class lower)\nValid TRCN registration — non-negotiable\n3–7 years of proven teaching experience at secondary level\nDemonstrated track record of strong student results in WAEC/NECO Mathematics\nExcellent classroom management and communication skills\nProficiency with digital teaching aids, projectors, and e-learning platforms\nAbility to teach Further Mathematics is an added advantage',
    perks: ['Health insurance', 'Annual performance bonus', 'Professional development budget', 'TRCN renewal support', 'End-of-year bonus', 'School fee discount for staff children'],
    applyInstructions: 'Send your CV (PDF, max 3 pages), a brief cover letter, and copies of your TRCN certificate and degree to careers@greenfield.edu.ng with subject: APPLICATION – Mathematics Teacher (SSS). Only shortlisted candidates will be contacted.',
  },
  {
    id:'v2', sId:'gf', sName:'Greenfield International School', sColor:'#1A3D2C',
    city:'Gwarinpa, Abuja', state:'FCT', dept:'Secondary – Academic', type:'Full-time',
    title:'Basic Science Teacher (JSS)', deadline:'25 Jul 2026',
    summary:'Passionate science teacher for JSS 1–3 with hands-on lab supervision experience and ability to inspire curiosity.',
    applyEmail:'careers@greenfield.edu.ng', trcnRequired: true,
    experienceLevel: 'Entry–Mid (1–5 years)', minQualification: 'B.Sc. / B.Ed.',
    salaryRange: '₦65k–₦90k/month', location: 'Gwarinpa, Abuja',
    roleOverview: 'We are looking for an enthusiastic Basic Science Teacher to spark scientific curiosity in our JSS 1–3 students. You will plan and deliver practical, inquiry-based lessons, manage the school\'s science laboratory safely, and lay a solid foundation for students\' future studies in Physics, Chemistry, and Biology. If you love igniting the wonder of discovery in young minds, this role is for you.',
    keyResponsibilities: 'Plan and deliver engaging Basic Science lessons for JSS 1–3 aligned with the NERDC curriculum\nConduct safe, well-supervised practical laboratory sessions\nPrepare students for BECE and Junior WAEC Basic Science examinations\nMaintain laboratory equipment, reagents, and safety standards in compliance with school policy\nSet and mark class assessments, tests, and terminal examinations\nTrack student progress and provide intervention for underperforming students\nCollaborate with the Science department on scheme of work and curriculum review\nOrganise and supervise science fairs and exhibitions for JSS students',
    requirements: 'B.Sc. or B.Ed. in Science Education, Biology, Chemistry, Physics, or a related field\nValid TRCN registration\n1–5 years of teaching experience at junior secondary level\nDemonstrated ability to conduct safe, engaging laboratory practicals\nStrong written and verbal communication skills\nComfort with e-learning tools and digital teaching resources\nAbility to teach any one of Physics, Chemistry, or Biology at SSS level is an advantage',
    perks: ['Health insurance', 'Annual performance bonus', 'Lab supply allowance', 'TRCN renewal support', 'End-of-year bonus', 'School fee discount for staff children'],
    applyInstructions: 'Email your CV and cover letter to careers@greenfield.edu.ng with subject: APPLICATION – Basic Science Teacher (JSS).',
  },
  {
    id:'v3', sId:'hc', sName:'Heritage College', sColor:'#2A6FDB',
    city:'Jabi, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Full-time',
    title:'School Librarian', deadline:'20 Jul 2026',
    summary:'Manage our growing library collection, catalogue acquisitions, and champion literacy across all year groups through a structured reading programme.',
    applyEmail:'hr@heritagecollege.edu.ng', trcnRequired: false,
    experienceLevel: 'Entry–Mid (1–4 years)', minQualification: 'B.Sc. / HND',
    salaryRange: '₦55k–₦75k/month', location: 'Jabi, Abuja',
    roleOverview: 'Heritage College invites applications from organised, detail-oriented individuals for the role of School Librarian. You will manage our growing library collection, create a welcoming reading environment for students and staff, and actively promote literacy across all year groups through our structured reading programme. This is a wonderful opportunity to shape the intellectual culture of a school that values deep, independent learning.',
    keyResponsibilities: 'Manage day-to-day library operations — circulation desk, opening/closing, and reading area upkeep\nCatalogue and classify new acquisitions using the Dewey Decimal System\nMaintain an up-to-date inventory of the library collection, including digital and audio resources\nImplement and coordinate the school-wide reading programme for all year groups\nAssist students and staff in locating resources for research and assignments\nOrganise book fairs, author visits, reading competitions, and World Book Day events\nEnsure library rules are observed and the environment remains quiet and productive\nLiaise with department heads to procure relevant textbooks and reference materials\nTrack overdue books and liaise with parents on replacements',
    requirements: 'Bachelor\'s degree or HND in Library Science, Information Management, or a related field\n1–4 years of experience in a school or public library preferred\nProficiency with library management software (or ability to learn quickly)\nStrong organisational and record-keeping skills\nPassion for books, literacy, and creating a love of reading in young people\nExcellent interpersonal skills for working with students, teachers, and parents\nAbility to work independently and manage multiple concurrent tasks',
    perks: ['Health insurance', 'Annual leave aligned with school calendar', 'Staff book allowance', 'Professional development support', 'End-of-year bonus', 'Stable hours — no weekend work'],
    applyInstructions: 'Send your CV and a short cover letter to hr@heritagecollege.edu.ng with subject: APPLICATION – School Librarian.',
  },
  {
    id:'v4', sId:'ms', sName:'Model Schools FCT', sColor:'#1F8A5B',
    city:'Maitama, Abuja', state:'FCT', dept:'Administration', type:'Full-time',
    title:'ICT Coordinator', deadline:'15 Jul 2026',
    summary:'Keep our computer lab and school-wide digital infrastructure running at peak performance while supporting teachers in integrating technology into their lessons.',
    applyEmail:'admin@modelschools.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (3–6 years)', minQualification: 'B.Sc.',
    salaryRange: '₦90k–₦130k/month', location: 'Maitama, Abuja',
    roleOverview: 'Model Schools FCT is seeking a tech-savvy, proactive ICT Coordinator to manage our computer laboratory and broader digital learning infrastructure. You will keep systems running at peak performance, support teachers in integrating technology into their lessons, and ensure students have access to a safe and productive digital learning environment. This is an exciting role for someone who thrives at the intersection of technology and education.',
    keyResponsibilities: 'Manage and maintain the school computer laboratory — hardware, software, and network infrastructure\nEnsure all student devices, projectors, and classroom technology are functional and up to date\nSupport teachers across departments with digital tools, e-learning platforms, and presentation technology\nInstall, configure, and update educational software and licences (Google Workspace, Microsoft 365, etc.)\nMonitor and enforce the school\'s safe internet use policy for students and staff\nTroubleshoot technical issues promptly and coordinate with external vendors for repairs\nDeliver ICT literacy sessions for junior secondary students as part of the curriculum\nMaintain an ICT asset register and oversee device procurement and disposal\nOrganise coding clubs, technology competitions, and digital skills workshops',
    requirements: 'B.Sc. in Computer Science, Information Technology, or a related field\n3–6 years of ICT support or administration experience, preferably in an educational setting\nStrong knowledge of Windows/macOS administration, networking fundamentals, and Google Workspace\nExperience troubleshooting hardware and software issues efficiently\nFamiliarity with school management systems and e-learning platforms is an advantage\nExcellent communication skills — able to explain technical concepts to non-technical staff\nPatience and a genuine interest in supporting teachers and students with technology',
    perks: ['Health insurance', 'Annual performance bonus', 'Housing allowance', 'Professional development and certification support', 'Laptop provided', 'End-of-year bonus'],
    applyInstructions: 'Email your CV and cover letter to admin@modelschools.edu.ng with subject: APPLICATION – ICT Coordinator.',
  },
  {
    id:'v5', sId:'ms', sName:'Model Schools FCT', sColor:'#1F8A5B',
    city:'Maitama, Abuja', state:'FCT', dept:'Secondary – Academic', type:'Full-time',
    title:'English Language Teacher', deadline:'10 Aug 2026',
    summary:'Articulate, inspiring English teacher for JSS and SSS. 3+ years required with strong WAEC preparation track record.',
    applyEmail:'admin@modelschools.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (3–7 years)', minQualification: 'B.A. / B.Ed.',
    salaryRange: '₦75k–₦110k/month', location: 'Maitama, Abuja',
    roleOverview: 'Model Schools FCT is looking for an articulate, inspiring English Language Teacher to deliver excellent language instruction across JSS and SSS. You will build students\' reading, writing, comprehension, and oral communication skills while preparing them rigorously for WAEC and NECO English Language examinations. If you have a passion for language, storytelling, and helping students find their voice, we want to hear from you.',
    keyResponsibilities: 'Deliver engaging English Language lessons for JSS 1–3 and SSS 1–3\nPrepare students for WAEC/NECO English Language and Literature papers\nTeach reading comprehension, summary writing, essay composition, letter writing, and oral English\nSet and mark weekly comprehension passages, compositions, and grammar exercises\nMonitor student writing development and provide structured written feedback\nConduct remedial reading and writing sessions for students who need extra support\nCollaborate with the English department on scheme of work, textbook review, and curriculum mapping\nOrganise debating, public speaking, spelling bee, and creative writing competitions',
    requirements: 'B.A. or B.Ed. in English Language, English Education, or Linguistics (minimum second class)\nValid TRCN registration\n3–7 years of secondary school teaching experience\nStrong knowledge of WAEC/NECO English syllabus and past-question analysis\nExcellent spoken and written English — a language role model for students\nProficiency with digital teaching tools and presentation software\nExperience coaching debate or public speaking teams is an advantage',
    perks: ['Health insurance', 'Annual performance bonus', 'TRCN renewal support', 'Professional development budget', 'End-of-year bonus', 'School fee discount for staff children'],
    applyInstructions: 'Send your CV, cover letter, and TRCN certificate to admin@modelschools.edu.ng with subject: APPLICATION – English Language Teacher.',
  },
  {
    id:'v6', sId:'ms', sName:'Model Schools FCT', sColor:'#1F8A5B',
    city:'Maitama, Abuja', state:'FCT', dept:'Administration', type:'Full-time',
    title:'School Accountant', deadline:'5 Aug 2026',
    summary:'Oversee fee collection, payroll processing, monthly financial reporting, and external audit coordination for a thriving multi-section school.',
    applyEmail:'admin@modelschools.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (3–6 years)', minQualification: 'B.Sc. / HND',
    salaryRange: '₦100k–₦150k/month', location: 'Maitama, Abuja',
    roleOverview: 'Model Schools FCT is seeking an experienced, detail-oriented School Accountant to manage the school\'s day-to-day financial operations. You will oversee school fee collection and reconciliation, process payroll, maintain accurate ledgers, and produce timely monthly financial reports for school management. This is a role that demands both numerical precision and the integrity required when handling an institution\'s finances.',
    keyResponsibilities: 'Manage the daily collection, recording, and reconciliation of school fees and levies\nProcess monthly payroll for all academic and non-academic staff\nMaintain up-to-date accounts payable and receivable ledgers\nPrepare monthly, termly, and annual financial reports for the School Director\nTrack fee arrears and coordinate follow-up with the bursar\'s office and parents\nReconcile bank statements and ensure all transactions are accurately captured\nManage petty cash and maintain proper documentation of all expenditure\nLiaise with external auditors during the annual audit\nEnsure financial operations comply with relevant tax and regulatory requirements\nSupport the management team with ad-hoc financial analysis and budgeting',
    requirements: 'B.Sc. or HND in Accounting, Finance, or a related field\nICANStudent membership or full ICAN qualification is a strong advantage\n3–6 years of accounting experience, preferably in a school or educational institution\nProficiency with accounting software (QuickBooks, Sage, or similar)\nStrong Microsoft Excel skills for financial modelling and reporting\nHigh level of integrity and discretion with confidential financial information\nExcellent attention to detail and organisational skills',
    perks: ['Health insurance', 'Annual performance bonus', 'Housing allowance', 'End-of-year bonus', 'ICAN study support and CPD budget', 'Stable working hours'],
    applyInstructions: 'Email your CV, cover letter, and professional certificates to admin@modelschools.edu.ng with subject: APPLICATION – School Accountant.',
  },
  {
    id:'v7', sId:'rb', sName:'Rainbow Nursery & Primary', sColor:'#D4591A',
    city:'Wuse II, Abuja', state:'FCT', dept:'Nursery – Academic', type:'Full-time',
    title:'Nursery Class Teacher', deadline:'1 Aug 2026',
    summary:'Warm, creative Nursery teacher for Pre-Nursery and Nursery 1–2. Montessori-trained candidates given priority.',
    applyEmail:'jobs@rainbownursery.edu.ng', trcnRequired: true,
    experienceLevel: 'Entry–Mid (1–4 years)', minQualification: 'NCE / B.Ed.',
    salaryRange: '₦55k–₦80k/month', location: 'Wuse II, Abuja',
    roleOverview: 'Rainbow Nursery & Primary School is looking for a warm, patient, and creative Nursery Class Teacher to join our early childhood education team. You will nurture Pre-Nursery and Nursery 1–2 children during their most formative learning years, delivering play-based, child-centred lessons that build literacy, numeracy, social, and fine motor skills. Candidates with Montessori training or experience will be given preference.',
    keyResponsibilities: 'Plan and deliver age-appropriate, play-based lessons for Pre-Nursery and Nursery 1–2\nCreate a safe, stimulating, and nurturing classroom environment each day\nMonitor each child\'s developmental milestones and maintain detailed progress records\nCommunicate regularly with parents through termly reports and parent meetings\nDesign activities that develop fine and gross motor skills, early language, and pre-literacy/numeracy\nSupervise children during outdoor play, meals, and all school activities\nPrepare end-of-term reports and learning portfolios for each child\nCollaborate with the ECCE coordinator on curriculum planning and seasonal themes\nManage the classroom with warmth, consistency, and positive behaviour strategies',
    requirements: 'NCE in Early Childhood Education, or B.Ed. in Education (ECCE or Primary Education)\nValid TRCN registration\n1–4 years of experience teaching pre-school or nursery classes\nMontessori certification or training is a strong advantage\nGenuine love for young children and patience in a nursery environment\nStrong parent communication skills — written and spoken\nAbility to create imaginative, hands-on learning activities',
    perks: ['Health insurance', 'Annual performance bonus', 'TRCN renewal support', 'End-of-year bonus', 'School fee discount for staff children', 'Supportive, family-friendly work environment'],
    applyInstructions: 'Send your CV and a brief cover letter expressing your approach to early childhood education to jobs@rainbownursery.edu.ng with subject: APPLICATION – Nursery Class Teacher.',
  },
  {
    id:'v8', sId:'cv', sName:'Covenant Academy', sColor:'#7C3AED',
    city:'Lugbe, Abuja', state:'FCT', dept:'Secondary – Academic', type:'Full-time',
    title:'Physical Education Teacher', deadline:'25 Jul 2026',
    summary:'Dynamic PE teacher to deliver the curriculum across JSS–SSS, coach school sports teams, and coordinate inter-house events.',
    applyEmail:'hr@covenantacademy.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (2–6 years)', minQualification: 'B.Sc. / B.Ed.',
    salaryRange: '₦70k–₦100k/month', location: 'Lugbe, Abuja',
    roleOverview: 'Covenant Academy is seeking a dynamic and sporty Physical Education Teacher to deliver our PE curriculum across JSS and SSS and lead our school sports programme. You will instil a lifelong love of physical activity and teamwork in our students, coach our school sports teams, and coordinate inter-house sports competitions. The ideal candidate combines coaching expertise with the discipline and enthusiasm to inspire young athletes.',
    keyResponsibilities: 'Plan and deliver Physical Education lessons for JSS 1–3 and SSS 1–3 in line with the NERDC curriculum\nCoach school football, basketball, and athletics teams for inter-school competitions\nOrganise and oversee the annual inter-house sports events, sports day, and field days\nEnsure sports equipment is maintained, stored safely, and replenished as needed\nMonitor student fitness progress and maintain PE assessment records\nPromote health, wellness, and positive sporting values throughout the school\nSupervise students safely during all physical activities and ensure first-aid readiness\nCollaborate with administration on the sporting calendar and budget\nLiaise with parents of students selected for representative sports teams',
    requirements: 'B.Sc. or B.Ed. in Physical Education, Sports Science, or Education with a PE specialisation\nValid TRCN registration\n2–6 years of teaching or coaching experience at secondary school level\nCoaching certification in any major sport (football, basketball, athletics) is an advantage\nStrong organisational skills for managing large events and competitions\nFirst Aid / CPR certification is desirable\nPhysically fit, energetic, and a positive role model for students',
    perks: ['Health insurance', 'Annual performance bonus', 'Sports kit allowance', 'TRCN renewal support', 'End-of-year bonus', 'Free gym / fitness area access on campus'],
    applyInstructions: 'Email your CV and cover letter to hr@covenantacademy.edu.ng with subject: APPLICATION – Physical Education Teacher.',
  },
  {
    id:'v9', sId:'cv', sName:'Covenant Academy', sColor:'#7C3AED',
    city:'Lugbe, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Full-time',
    title:'School Nurse', deadline:'18 Jul 2026',
    summary:'Qualified RN to manage the school sick bay, administer first aid, respond to emergencies, and maintain comprehensive student health records.',
    applyEmail:'hr@covenantacademy.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (2–5 years)', minQualification: 'B.Sc. Nursing / RN',
    salaryRange: '₦90k–₦130k/month', location: 'Lugbe, Abuja',
    roleOverview: 'Covenant Academy is looking for a compassionate, qualified School Nurse to provide first-line healthcare support for our students and staff. You will manage the school sick bay, administer first aid and prescribed medications, maintain comprehensive student health records, and be the calm, professional first responder to any medical emergency on campus. Your presence will be a daily reassurance to students, parents, and staff.',
    keyResponsibilities: 'Manage the school sick bay — ensure it is clean, fully stocked, and fit for purpose at all times\nAdminister first aid and basic healthcare to sick or injured students and staff\nMaintain accurate health records for every student — allergies, conditions, and medication histories\nDispense prescribed medications in accordance with parental authorisation and school policy\nConduct termly health screenings (vision, hearing, weight/height) for students\nRespond promptly and calmly to on-campus medical emergencies and coordinate hospital transfers when needed\nEducate students on hygiene, nutrition, and general wellness through scheduled health talks\nLiaise with parents and guardians on individual student health matters\nEnsure first aid kits, AED, and emergency supplies are fully stocked at all times\nCompile and submit termly health and wellness reports to school management',
    requirements: 'B.Sc. Nursing or Registered Nurse (RN) licence from the Nursing and Midwifery Council of Nigeria\n2–5 years of nursing experience; school nursing or paediatric experience is preferred\nValid BLS / First Aid certification — must be current\nCalm, empathetic, and decisive under pressure\nStrong record-keeping and medical report-writing skills\nAbility to communicate sensitively with students, parents, and teachers\nResidence within reasonable distance of the school is an advantage',
    perks: ['Health insurance', 'Annual performance bonus', 'Medical uniform allowance', 'End-of-year bonus', 'Nursing CPD support', 'Stable hours aligned with the school calendar'],
    applyInstructions: 'Send your CV, RN licence, BLS certificate, and cover letter to hr@covenantacademy.edu.ng with subject: APPLICATION – School Nurse.',
  },
  {
    id:'v10', sId:'li', sName:'Lagos International School', sColor:'#C41E3A',
    city:'Victoria Island', state:'Lagos', dept:'Secondary – Academic', type:'Full-time',
    title:'Head of Science Department', deadline:'15 Aug 2026',
    summary:'Senior academic leader to lead the Science faculty, mentor teachers, manage the lab, and drive consistently strong WAEC/NECO outcomes.',
    applyEmail:'recruitment@lagosintl.edu.ng', trcnRequired: true,
    experienceLevel: 'Senior (7+ years)', minQualification: 'B.Sc. / M.Sc.',
    salaryRange: '₦150k–₦220k/month', location: 'Victoria Island, Lagos',
    roleOverview: 'Lagos International School is seeking an experienced, visionary Head of Science Department to lead our Science faculty. This senior academic role requires someone who combines deep scientific knowledge with the ability to mentor teachers, drive curriculum excellence, and deliver outstanding student outcomes in Physics, Chemistry, and Biology. You will shape the scientific culture of one of Lagos\' most respected schools and inspire the next generation of Nigerian scientists.',
    keyResponsibilities: 'Lead and manage the Science department — overseeing Physics, Chemistry, and Biology teachers\nDevelop, review, and implement the Science curriculum for JSS and SSS aligned with NERDC and WAEC standards\nConduct lesson observations and provide structured coaching and feedback to science staff\nCoordinate school-wide WAEC/NECO examination preparation and past-question analysis\nManage the science laboratory — safety, equipment maintenance, and adequate supply of reagents\nPrepare and manage the department\'s annual budget in collaboration with school management\nChair departmental meetings and maintain accurate department records\nLiaise with the Principal on academic quality assurance and departmental performance targets\nOrganise the school science fair, inter-school competitions, and science exhibitions\nRepresent the department on the Academic Committee',
    requirements: 'B.Sc. and ideally M.Sc. in Physics, Chemistry, Biology, or a combined science discipline\nValid TRCN registration with evidence of leadership endorsement\nMinimum 7 years\' teaching experience, at least 3 in a Head of Department or senior academic role\nDemonstrated track record of consistently strong WAEC/NECO science results\nStrong leadership, mentoring, and curriculum development skills\nExcellent organisational and communication skills\nFamiliarity with Cambridge IGCSE or other international science frameworks is an advantage',
    perks: ['Health insurance for self and dependants', 'Annual performance bonus', 'Housing allowance', 'Professional development budget ₦200,000 p.a.', 'Free school placement for one child', 'TRCN renewal support', 'End-of-year bonus'],
    applyInstructions: 'Email a detailed CV (max 4 pages), cover letter, and relevant certificates to recruitment@lagosintl.edu.ng with subject: APPLICATION – Head of Science Department.',
  },
  {
    id:'v11', sId:'li', sName:'Lagos International School', sColor:'#C41E3A',
    city:'Victoria Island', state:'Lagos', dept:'Administration', type:'Full-time',
    title:'IT Systems Administrator', deadline:'20 Aug 2026',
    summary:'Mission-critical IT role managing the school\'s network, servers, student devices, and digital infrastructure for a 1,200-student campus.',
    applyEmail:'recruitment@lagosintl.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (3–7 years)', minQualification: 'B.Sc.',
    salaryRange: '₦120k–₦180k/month', location: 'Victoria Island, Lagos',
    roleOverview: 'Lagos International School is looking for a skilled IT Systems Administrator to maintain and grow our digital infrastructure. You will keep our network, servers, student devices, and software systems running reliably — ensuring teachers and students have seamless access to technology every school day. This is a mission-critical operations role for someone who takes pride in keeping complex systems running smoothly and responds quickly when issues arise.',
    keyResponsibilities: 'Administer and maintain the school\'s LAN/Wi-Fi network, servers, and internet connectivity\nManage and support student and staff devices — laptops, desktops, tablets, projectors\nAdminister Google Workspace for Education accounts for 1,200+ staff and students\nInstall, patch, and update operating systems, software, and security tools\nMonitor network performance, uptime, and security — respond promptly to any issues\nMaintain tested backups of critical school data and disaster recovery procedures\nEnforce the school\'s IT acceptable use policy and safeguarding controls\nLiaise with ISPs, hardware vendors, and software suppliers\nSupport teachers with classroom technology integration\nMaintain the IT asset register and manage device procurement lifecycle',
    requirements: 'B.Sc. in Computer Science, Network Engineering, Information Technology, or related field\n3–7 years of IT administration or systems support experience\nStrong knowledge of Windows Server, TCP/IP networking, and Google Workspace administration\nExperience with network switches, firewalls, and Wi-Fi access point configuration\nCompTIA Network+, MCSA, or equivalent certification is an advantage\nAbility to diagnose and resolve hardware and software issues quickly\nExcellent documentation habits and communication skills',
    perks: ['Health insurance', 'Annual performance bonus', 'Housing allowance', 'Laptop and tools provided', 'Professional certification support budget', 'End-of-year bonus'],
    applyInstructions: 'Send your CV and professional certifications to recruitment@lagosintl.edu.ng with subject: APPLICATION – IT Systems Administrator.',
  },
  {
    id:'v12', sId:'li', sName:'Lagos International School', sColor:'#C41E3A',
    city:'Victoria Island', state:'Lagos', dept:'Secondary – Academic', type:'Part-time',
    title:'French Teacher (JSS + SSS)', deadline:'10 Aug 2026',
    summary:'Fluent French teacher needed part-time (approx. 15 periods/week) to deliver the curriculum and prepare SSS students for WAEC French.',
    applyEmail:'recruitment@lagosintl.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (2–6 years)', minQualification: 'B.A. / B.Ed.',
    salaryRange: '₦45k–₦70k/month', location: 'Victoria Island, Lagos',
    roleOverview: 'Lagos International School is seeking a fluent, culturally informed French Teacher on a part-time basis to deliver the French language curriculum across JSS and SSS classes. You will build students\' conversational fluency, grammatical accuracy, and cultural appreciation of the Francophone world, while preparing SSS students for the WAEC French paper. Ideal for an experienced teacher who values a flexible, timetabled part-time schedule.',
    keyResponsibilities: 'Deliver structured French lessons for JSS 1–3 and SSS 1–3 (approximately 15–18 periods per week)\nPrepare SSS students for WAEC and NECO French Language papers — oral and written components\nTeach oral French, reading comprehension, grammar, composition, and translation skills\nSet and mark regular class tests, assignments, and terminal examinations\nOrganise French culture activities, language competitions, and Francophonie Day events\nMaintain student progress records and submit termly reports\nCollaborate with the Languages HoD on scheme of work and curriculum alignment',
    requirements: 'B.A. or B.Ed. in French, Modern Languages, or French Education\nNear-native French proficiency (DELF/DALF B2 or above preferred)\nValid TRCN registration\n2–6 years of secondary school French teaching experience\nStrong knowledge of the WAEC French syllabus and examination format\nEnthusiasm for French culture and communicative language teaching',
    perks: ['Flexible part-time schedule aligned with school timetable', 'Termly performance bonus', 'TRCN renewal support', 'Staff development days included'],
    applyInstructions: 'Send your CV and a brief note on your French language proficiency to recruitment@lagosintl.edu.ng with subject: APPLICATION – French Teacher.',
  },
  {
    id:'v13', sId:'hil', sName:'Hillcrest School', sColor:'#0D9D8A',
    city:'Jos, Plateau', state:'Plateau', dept:'Non-academic / Support', type:'Full-time',
    title:'Boarding House Master', deadline:'5 Aug 2026',
    summary:'Mature, residential pastoral leader to supervise boarding students, enforce house standards, and provide round-the-clock welfare support on the Hillcrest campus.',
    applyEmail:'staffing@hillcrest.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (2–5 years)', minQualification: 'B.A. / B.Sc.',
    salaryRange: '₦75k–₦110k/month + accommodation', location: 'Jos, Plateau State',
    roleOverview: 'Hillcrest School — one of Nigeria\'s historic mission boarding schools — is seeking a mature, responsible Boarding House Master to live on campus and provide round-the-clock supervision, pastoral care, and a safe home-away-from-home for our boarding students. You will enforce house rules with fairness and consistency, build strong relationships with students, and coordinate closely with academic staff to support each boarder\'s holistic development. On-campus accommodation is provided.',
    keyResponsibilities: 'Supervise the daily rhythm of boarding life — morning routines, prep periods, mealtimes, and lights-out\nEnforce house rules, maintain discipline, and foster a positive, respectful house culture\nProvide pastoral support to individual boarders — monitoring emotional wellbeing, homesickness, and personal growth\nCoordinate with class teachers and the school counsellor on student welfare cases\nOrganise house activities, competitions, and community service projects\nRespond to out-of-hours emergencies and medical situations, liaising with the school nurse\nConduct routine room inspections and ensure boarding areas are clean and well-maintained\nCommunicate regularly with parents about their child\'s boarding life and welfare\nMaintain the house roll book, incident log, and disciplinary records\nSupport the Dean of Students in policy compliance and boarding administration',
    requirements: 'A good first degree from a recognised university (any discipline)\n2–5 years of experience in boarding school supervision, youth work, or pastoral care\nSingle or willing to live on campus in the provided staff accommodation\nCalm, firm, and empathetic — able to handle adolescent behaviour with maturity and consistency\nFirst Aid certification is an advantage\nStrong written communication and report-writing skills\nCommitment to the school\'s Christian values and ethos',
    perks: ['On-campus accommodation provided', 'Meals included', 'Health insurance', 'Annual performance bonus', 'Annual leave', 'End-of-year bonus', 'Vibrant Jos school community'],
    applyInstructions: 'Send a detailed CV and a letter explaining your approach to student pastoral care to staffing@hillcrest.edu.ng with subject: APPLICATION – Boarding House Master.',
  },
  {
    id:'v14', sId:'ka', sName:"King's College Lagos", sColor:'#1E3A5F',
    city:'Lagos Island', state:'Lagos', dept:'Secondary – Academic', type:'Full-time',
    title:'History Teacher (JSS–SSS)', deadline:'28 Jul 2026',
    summary:'Exceptional History teacher to bring Nigerian, African, and World History to life at one of Nigeria\'s most prestigious secondary schools.',
    applyEmail:'hr@kingscollegelagos.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (3–7 years)', minQualification: 'B.A. / B.Ed.',
    salaryRange: '₦75k–₦110k/month', location: 'Lagos Island, Lagos',
    roleOverview: 'King\'s College Lagos — one of Nigeria\'s most prestigious secondary schools — is seeking an exceptional History Teacher to inspire students with a deep love of the past and a critical understanding of how history shapes the present. You will deliver compelling History lessons across JSS and SSS, prepare students rigorously for WAEC, and bring the stories of Nigeria and the wider world to life in your classroom. This is a rare opportunity to teach at one of the country\'s most storied institutions.',
    keyResponsibilities: 'Deliver inspiring History lessons for JSS 1–3 and SSS 1–3\nPrepare SSS students for WAEC and NECO History papers with structured past-question practice\nTeach Nigerian, African, and World History with depth, accuracy, and cultural sensitivity\nSet and mark essays, source-based questions, and terminal examinations\nDevelop students\' analytical writing, critical thinking, and oral discussion skills\nOrganise historical debates, quiz competitions, field trips to heritage sites, and documentary screenings\nMaintain accurate assessment records and submit timely student progress reports\nCollaborate with the Humanities HoD on curriculum planning and co-curricular activities',
    requirements: 'B.A. or B.Ed. in History, History and International Studies, or a related humanities discipline\nValid TRCN registration\n3–7 years of secondary school History teaching experience\nDemonstrated track record of strong WAEC/NECO History results\nExcellent essay-writing, analytical, and oral communication skills\nAbility to make historical content engaging and relevant to contemporary Nigerian students\nKnowledge of African history and post-independence Nigerian political history is essential',
    perks: ['Health insurance', 'Annual performance bonus', 'TRCN renewal support', 'Professional development budget', 'End-of-year bonus', 'School fee discount for staff children', 'Prestigious institution on your professional profile'],
    applyInstructions: 'Send your CV, a cover letter, and evidence of past student examination results to hr@kingscollegelagos.edu.ng with subject: APPLICATION – History Teacher.',
  },
  {
    id:'v15', sId:'ka', sName:"King's College Lagos", sColor:'#1E3A5F',
    city:'Lagos Island', state:'Lagos', dept:'Non-academic / Support', type:'Full-time',
    title:'Music Director', deadline:'1 Aug 2026',
    summary:'Talented conductor and music educator to direct the school choir and band, deliver the music curriculum, and lead all cultural performances at this iconic Lagos institution.',
    applyEmail:'hr@kingscollegelagos.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (3–8 years)', minQualification: 'B.Mus. / B.A.',
    salaryRange: '₦100k–₦150k/month', location: 'Lagos Island, Lagos',
    roleOverview: 'King\'s College Lagos is seeking a talented, passionate Music Director to lead and develop our school\'s music programme — one with a rich tradition stretching back decades. You will direct the school choir and band, deliver music education across year groups, and be the creative force behind cultural performances, Speech Day, and special events. This is an extraordinary role for a musician who wants to shape the cultural heartbeat of one of Nigeria\'s most iconic institutions.',
    keyResponsibilities: 'Direct, rehearse, and perform with the school choir and concert/brass band\nDeliver Music lessons for JSS and SSS students within the formal curriculum\nOrganise and oversee all school musical performances — Speech Day, Cultural Day, inter-school competitions, and chapel services\nAudition, recruit, and develop student musicians across instruments and voice types\nArrange and adapt pieces for school ensembles\nMaintain and manage musical instruments, sheet music, and audio equipment\nCoordinate with external music tutors for specialist instrumental instruction\nOrganise musical excursions, master classes, and workshops with visiting artists\nPrepare students for Music WAEC/NECO examinations where applicable\nSupport the school\'s broader cultural programme and inter-school cultural competitions',
    requirements: 'B.Mus. or B.A. in Music, Music Education, or Performing Arts\n3–8 years of conducting, directing, or music education experience\nProficiency in conducting choral and/or instrumental ensembles\nAbility to play at least one instrument to performance standard — piano preferred\nGood sight-reading skills and knowledge of both Western and African musical traditions\nStrong organisational skills for coordinating large-scale school events\nPassion for music education and inspiring young performers',
    perks: ['Health insurance', 'Annual performance bonus', 'Instrument allowance', 'Performance and professional development budget', 'End-of-year bonus', 'Prestigious platform for musical performance and direction'],
    applyInstructions: 'Send your CV, a cover letter, and a link to a recent performance or recording to hr@kingscollegelagos.edu.ng with subject: APPLICATION – Music Director.',
  },
  {
    id:'v16', sId:'bca', sName:'Bingham Academy', sColor:'#7A4A00',
    city:'Karu, Abuja', state:'FCT', dept:'Secondary – Academic', type:'Full-time',
    title:'Chemistry Teacher', deadline:'20 Aug 2026',
    summary:'Safety-conscious Chemistry teacher with strong practical teaching skills and a proven WAEC/NECO results record. TRCN registration required.',
    applyEmail:'jobs@binghamacademy.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (3–7 years)', minQualification: 'B.Sc. / B.Ed.',
    salaryRange: '₦80k–₦120k/month', location: 'Karu, Abuja',
    roleOverview: 'Bingham Academy is seeking an experienced, safety-conscious Chemistry Teacher to deliver rigorous and engaging instruction across JSS and SSS. You will blend theory with hands-on practical experimentation, prepare students comprehensively for WAEC and NECO Chemistry, and uphold the highest standards of laboratory safety. If you can make Chemistry exciting while keeping students safe and results strong, we want you on our team.',
    keyResponsibilities: 'Plan and deliver Chemistry lessons for JSS (Integrated Science) and SSS Chemistry 1–3\nConduct safe, well-managed practical sessions in the school chemistry laboratory\nPrepare students for WAEC/NECO Chemistry — theory and practical papers\nEnsure compliance with all laboratory safety protocols, chemical storage, and disposal procedures\nMaintain lab equipment and submit timely requests for reagent and consumable replenishment\nSet and mark assignments, class assessments, and terminal examinations\nTrack student progress and deliver targeted intervention for underperforming learners\nCollaborate with the Science HoD on curriculum, practical timetable, and exam preparation\nMentor junior science staff and contribute to science department activities',
    requirements: 'B.Sc. or B.Ed. in Chemistry, Chemistry Education, or Industrial Chemistry\nValid TRCN registration\n3–7 years of secondary school Chemistry teaching experience\nStrong and consistent WAEC/NECO Chemistry student results\nDemonstrated lab safety awareness and practical teaching competence\nAbility to teach Physics or Biology to JSS level is an advantage\nExcellent written and verbal communication skills',
    perks: ['Health insurance', 'Annual performance bonus', 'Laboratory supply allowance', 'TRCN renewal support', 'Professional development budget', 'End-of-year bonus'],
    applyInstructions: 'Email your CV, TRCN certificate, and cover letter to jobs@binghamacademy.edu.ng with subject: APPLICATION – Chemistry Teacher.',
  },
  {
    id:'v17', sId:'bca', sName:'Bingham Academy', sColor:'#7A4A00',
    city:'Karu, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Full-time',
    title:'Counsellor', deadline:'15 Aug 2026',
    summary:'Qualified school counsellor to provide emotional, academic, and career guidance to secondary students as a cornerstone of our pastoral care system.',
    applyEmail:'jobs@binghamacademy.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (2–6 years)', minQualification: 'B.Sc. / M.Sc.',
    salaryRange: '₦85k–₦125k/month', location: 'Karu, Abuja',
    roleOverview: 'Bingham Academy is looking for a compassionate, professionally qualified School Counsellor to support the emotional, social, academic, and career development of our secondary students. You will provide individual and group counselling sessions, manage referrals, work collaboratively with teachers and parents, and champion a whole-school approach to student mental health and wellbeing. This is a vital role at the heart of our pastoral care system.',
    keyResponsibilities: 'Provide individual counselling for students experiencing academic, emotional, social, or family challenges\nDeliver group guidance sessions on study skills, career exploration, peer relationships, and life skills\nConduct career guidance workshops for SSS students preparing for UTME and tertiary education\nMaintain confidential counselling records in compliance with ethical standards\nLiaise with teachers, parents, and external mental health professionals on escalated cases\nDesign and implement school-wide wellbeing programmes and awareness campaigns\nSupport the school\'s anti-bullying policy and mediate peer conflict\nOrganise career fairs, alumni mentoring sessions, and university application support workshops\nSubmit termly wellbeing reports to school management\nRepresent the counselling department on the pastoral care committee',
    requirements: 'B.Sc. in Psychology, Guidance and Counselling, or a related field\nM.Sc. in Counselling Psychology, Educational Psychology, or School Counselling is a strong advantage\nNigerian Board of Professional Psychology (NBCP) registration or eligibility\n2–6 years of professional counselling experience, preferably with adolescents\nStrong empathy, active listening, and crisis management skills\nAbility to maintain strict confidentiality while escalating safeguarding concerns appropriately\nExcellent communication skills with students, parents, and teachers',
    perks: ['Health insurance', 'Annual performance bonus', 'CPD and professional development budget', 'Clinical supervision support', 'End-of-year bonus', 'Stable, meaningful work in a supportive school community'],
    applyInstructions: 'Email your CV, evidence of professional registration, and a cover letter to jobs@binghamacademy.edu.ng with subject: APPLICATION – School Counsellor.',
  },
  {
    id:'v18', sId:'bca', sName:'Bingham Academy', sColor:'#7A4A00',
    city:'Karu, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Part-time',
    title:'Swimming Coach', deadline:'10 Aug 2026',
    summary:'Certified swimming coach and lifeguard to train the school swim team, manage pool safety, and represent the school at inter-school galas.',
    applyEmail:'jobs@binghamacademy.edu.ng', trcnRequired: false,
    experienceLevel: 'Entry–Mid (1–4 years)', minQualification: 'Coaching Cert',
    salaryRange: '₦40k–₦60k/month', location: 'Karu, Abuja',
    roleOverview: 'Bingham Academy is seeking an experienced and safety-certified Swimming Coach (part-time, ~15 hours/week) to train our school swim team, manage pool operations, and represent the school at inter-school swimming competitions. This role is ideal for a qualified swimmer-coach who wants to combine their passion for the sport with the reward of developing young athletic talent.',
    keyResponsibilities: 'Coach the school swim team across all age groups (JSS and SSS)\nDeliver beginner and intermediate swimming lessons for students learning to swim\nManage pool safety — conduct pre-session risk assessments and enforce pool rules at all times\nPrepare and enter the school team in inter-school swimming galas and competitions\nRecord student swimming progress and submit reports to the sports coordinator\nMaintain pool equipment (lane ropes, kickboards, timing devices) and report maintenance needs\nLiaise with parents of competitive swimmers on training schedules and competition dates\nSupport the school sports day with aquatic event coordination',
    requirements: 'Recognised swimming coaching certificate (ICAN Level 1 or equivalent) — required\nValid lifeguard certification (Red Cross, RLSS, or equivalent) — non-negotiable\n1–4 years of coaching or swimming instruction experience\nStrong swimming ability and technique knowledge across all four competitive strokes\nCalm, safety-first approach — comfortable managing groups of children around water\nBasic First Aid and CPR certification',
    perks: ['Flexible part-time schedule', 'Termly performance bonus', 'Pool access during off-peak hours', 'Swimwear/uniform provided', 'End-of-year bonus'],
    applyInstructions: 'Send your CV, coaching certificate, and lifeguard certification to jobs@binghamacademy.edu.ng with subject: APPLICATION – Swimming Coach.',
  },
  {
    id:'v19', sId:'ld', sName:'Ladela Schools', sColor:'#065F46',
    city:'Surulere, Lagos', state:'Lagos', dept:'Primary – Academic', type:'Full-time',
    title:'Primary Class Teacher (Yr 4–6)', deadline:'5 Aug 2026',
    summary:'Dedicated, creative upper primary teacher to manage a Year 4, 5, or 6 class, with a strong focus on literacy development and holistic child growth.',
    applyEmail:'careers@ladelaschools.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (2–6 years)', minQualification: 'NCE / B.Ed.',
    salaryRange: '₦70k–₦100k/month', location: 'Surulere, Lagos',
    roleOverview: 'Ladela Schools is looking for a dedicated, creative Primary Class Teacher to manage an upper primary class (Year 4, 5, or 6). You will deliver engaging cross-curricular lessons, nurture each child\'s literacy and numeracy development, and create a warm, inclusive classroom where every learner can thrive. We value teachers who go beyond syllabus delivery to truly know their students and spark a lifelong love of learning.',
    keyResponsibilities: 'Plan and deliver effective lessons across all primary subjects for Year 4–6 students\nPromote strong literacy and numeracy skills as foundations for senior school readiness\nCreate and maintain a stimulating, organised, and inclusive classroom environment\nConduct formative and summative assessments; mark classwork and homework regularly\nPrepare comprehensive end-of-term progress reports for parents\nCommunicate proactively with parents on student progress, behaviour, and development\nParticipate in staff meetings, parent–teacher conferences, and school development days\nContribute to extracurricular activities, school clubs, and inter-house events\nCoordinate with the Year Head on curriculum mapping and cross-class initiatives',
    requirements: 'NCE in Primary Education, or B.Ed. in Education (Primary or any subject specialisation)\nValid TRCN registration\n2–6 years of teaching experience in upper primary (Year 4–6 or Primary 4–6)\nStrong literacy and numeracy instruction skills\nAbility to differentiate learning for mixed-ability classrooms\nPositive, patient, and nurturing approach to child development\nStrong written communication skills for report writing and parent engagement',
    perks: ['Health insurance', 'Annual performance bonus', 'TRCN renewal support', 'Professional development budget', 'End-of-year bonus', 'School fee discount for staff children', 'Supportive, collaborative team'],
    applyInstructions: 'Send your CV and a cover letter to careers@ladelaschools.edu.ng with subject: APPLICATION – Primary Class Teacher (Yr 4–6).',
  },
  {
    id:'v20', sId:'ld', sName:'Ladela Schools', sColor:'#065F46',
    city:'Surulere, Lagos', state:'Lagos', dept:'Administration', type:'Full-time',
    title:'Vice Principal (Academics)', deadline:'30 Jul 2026',
    summary:'Senior academic leadership role overseeing the curriculum, timetable, teacher appraisals, and exam preparation across all sections of a growing Lagos school.',
    applyEmail:'careers@ladelaschools.edu.ng', trcnRequired: true,
    experienceLevel: 'Senior (7+ years)', minQualification: 'M.Ed. / M.Sc.',
    salaryRange: '₦200k–₦280k/month', location: 'Surulere, Lagos',
    roleOverview: 'Ladela Schools (Surulere) is seeking a seasoned academic leader to serve as Vice Principal (Academics). You will partner with the Principal to drive academic excellence, oversee the school timetable, lead teacher performance reviews, and ensure curriculum quality from nursery through senior secondary. This is a senior executive role for an educator who has already built a strong record of improving student outcomes at scale and is ready to lead a large, diverse school community.',
    keyResponsibilities: 'Oversee the academic programme for all sections — Nursery, Primary, and Secondary\nDesign and manage the school timetable — scheduling, cover arrangements, and exam timetabling\nLead teacher appraisals, lesson observations, and structured coaching conversations\nDrive curriculum planning, scheme of work reviews, and academic quality assurance\nCoordinate all public examination preparations — WAEC, NECO, Common Entrance, UTME\nLine-manage Heads of Department and chair the Academic Committee\nAnalyse student performance data and implement targeted improvement strategies\nHandle escalated parent consultations on academic matters\nSupport the Principal in accreditation, strategic planning, and regulatory compliance\nRepresent the school at academic forums and examination body events',
    requirements: 'Master\'s degree in Education, Educational Administration, or a relevant subject discipline\nValid TRCN registration with leadership endorsement\nMinimum 7 years\' teaching experience; at least 3 years in a Head of Department or senior academic leadership role\nDemonstrated ability to improve student examination outcomes at whole-school level\nOutstanding people management, communication, and stakeholder engagement skills\nStrong analytical and data-interpretation skills for performance monitoring\nFamiliarity with Nigerian school regulatory frameworks (NERDC, NECO, WAEC) is essential',
    perks: ['Health insurance for self and spouse', 'Annual performance bonus', 'Housing allowance', 'Professional development budget ₦250,000 p.a.', 'Vehicle or transport allowance', 'Free school placement for up to 2 children', 'End-of-year bonus'],
    applyInstructions: 'Applications must include: (1) a detailed CV (max 4 pages) and (2) a one-page statement of your academic leadership philosophy. Send to careers@ladelaschools.edu.ng with subject: APPLICATION – Vice Principal (Academics). Closing date: 30 July 2026.',
  },
  {
    id:'v21', sId:'sfd', sName:'FCT School for the Deaf', sColor:'#2A6FDB',
    city:'Karu, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Full-time',
    title:'Sign Language Interpreter', deadline:'28 Jul 2026',
    summary:'Fluent NSL interpreter to provide real-time interpretation across classrooms, assemblies, parent meetings, and school events for our deaf and hard-of-hearing students.',
    applyEmail:'hr@fctdeafschool.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (2–5 years)', minQualification: 'Diploma / B.Sc.',
    salaryRange: '₦80k–₦120k/month', location: 'Karu, Abuja',
    roleOverview: 'FCT School for the Deaf provides world-class education to deaf and hard-of-hearing students in Abuja. We are seeking a skilled Sign Language Interpreter to ensure full classroom access for our students. You will interpret for teachers and students in lessons, assemblies, parent meetings, and events — ensuring our deaf students receive the same quality of instruction and communication as their hearing peers. This is a profoundly meaningful role for someone fluent in Nigerian Sign Language (NSL).',
    keyResponsibilities: 'Provide accurate real-time sign language interpretation across all classroom lessons for every subject\nInterpret at assemblies, staff meetings, parent–teacher conferences, and school events\nWork closely with class teachers to prepare for upcoming lessons and clarify technical vocabulary in advance\nSupport deaf students in understanding and completing written assignments\nInterpret in administrative meetings, counselling sessions, and disciplinary proceedings involving deaf students\nModel clear, expressive NSL to support student language development\nMaintain professional neutrality and strict confidentiality in all interpreted settings\nParticipate in staff training on deaf inclusion and communication strategies',
    requirements: 'Recognised qualification in Sign Language Interpretation (Diploma or Degree level)\nFluency in Nigerian Sign Language (NSL) — essential; British Sign Language (BSL) is an advantage\nRegistration with the Sign Language Interpreters Network of Nigeria (SLINN) or equivalent\n2–5 years of professional sign language interpretation experience, preferably in an educational setting\nStrong ethical standards and adherence to the Code of Professional Conduct for Interpreters\nPatience, cultural sensitivity, and genuine commitment to deaf inclusion\nAbility to prepare for specialised content across all secondary school subject areas',
    perks: ['Health insurance', 'Annual performance bonus', 'Professional development and CPD budget', 'End-of-year bonus', 'Meaningful, impactful work in a specialist educational environment'],
    applyInstructions: 'Send your CV, sign language qualification, and a cover letter to hr@fctdeafschool.edu.ng with subject: APPLICATION – Sign Language Interpreter.',
  },
  {
    id:'v22', sId:'sfd', sName:'FCT School for the Deaf', sColor:'#2A6FDB',
    city:'Karu, Abuja', state:'FCT', dept:'Non-academic / Support', type:'Contract',
    title:'Speech Therapist', deadline:'15 Aug 2026',
    summary:'MRTBN-registered Speech Therapist for weekly on-site sessions supporting students with hearing loss, cochlear implants, and residual hearing who benefit from structured speech rehabilitation.',
    applyEmail:'hr@fctdeafschool.edu.ng', trcnRequired: false,
    experienceLevel: 'Mid-level (2–5 years)', minQualification: 'B.Sc.',
    salaryRange: '₦15k–₦25k/session', location: 'Karu, Abuja',
    roleOverview: 'FCT School for the Deaf is seeking a qualified Speech Therapist on a contract basis to provide regular, professional speech and language therapy to our students. Many of our students have residual hearing, cochlear implants, or hearing aids and benefit significantly from targeted speech therapy. You will assess each student\'s communication profile, design individual therapy plans, and collaborate closely with teachers and parents to maximise spoken language outcomes.',
    keyResponsibilities: 'Conduct formal and informal speech and language assessments for new students and annual reviews for existing students\nDesign and deliver individualised therapy programmes for students with varying hearing and communication profiles\nConduct weekly one-on-one and small-group therapy sessions on campus\nSet measurable communication goals and monitor progress against them termly\nPrepare clear, detailed termly reports on each student\'s speech and language development\nProvide practical guidance to teachers on supporting students\' communication in the classroom\nLiaise with parents to explain therapy goals and provide home-practice strategies\nKeep accurate, confidential therapy records\nAttend IEP (Individual Education Plan) meetings where communication is a focus',
    requirements: 'B.Sc. in Speech-Language Therapy or Speech and Language Pathology\nRegistration with the Medical Rehabilitation Therapists Board of Nigeria (MRTBN) — required\n2–5 years of clinical experience, preferably with deaf or hard-of-hearing clients or in a school setting\nKnowledge of audiology, cochlear implant rehabilitation, and hearing aid support is an advantage\nAbility to adapt assessment and therapy techniques for children of different ages\nStrong interpersonal and report-writing skills\nBasic knowledge of sign language is an advantage',
    perks: ['Competitive per-session contract rate', 'Flexible scheduling (weekly school visits)', 'Meaningful clinical experience in a specialist educational setting', 'CPD opportunities with specialist deaf education staff'],
    applyInstructions: 'Send your CV, MRTBN registration, and a brief cover letter to hr@fctdeafschool.edu.ng with subject: APPLICATION – Speech Therapist (Contract).',
  },
  {
    id:'v23', sId:'sts', sName:'Stepping Stones Special School', sColor:'#D97757',
    city:'Ikeja, Lagos', state:'Lagos', dept:'Primary – Academic', type:'Full-time',
    title:'Special Education Teacher (Dyslexia)', deadline:'20 Aug 2026',
    summary:'Specialist educator with dyslexia assessment and structured literacy intervention experience to design and deliver personalised learning programmes for students with reading difficulties.',
    applyEmail:'jobs@steppingstones.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (2–6 years)', minQualification: 'B.Ed. / B.Sc.',
    salaryRange: '₦90k–₦130k/month', location: 'Ikeja, Lagos',
    roleOverview: 'Stepping Stones Special School is dedicated to providing excellent, individualised education for children with learning differences. We are seeking a qualified and empathetic Special Education Teacher with expertise in dyslexia and reading difficulties. You will conduct assessments, design tailored literacy intervention programmes, deliver one-on-one and small-group sessions, and collaborate closely with parents to give every student the tools they need to read, write, and flourish.',
    keyResponsibilities: 'Conduct formal and informal literacy assessments to identify specific learning profiles and dyslexia indicators\nDesign and implement individualised programmes using evidence-based dyslexia intervention approaches (Orton-Gillingham, Read Write Inc., Wilson Reading, or similar)\nDeliver structured one-on-one and small-group literacy intervention sessions\nTrack student progress against defined targets and adjust programmes as needed\nPrepare detailed Individual Education Plans (IEPs) and review them termly with parents and the SENCO\nCollaborate with classroom teachers on support strategies and reasonable examination adjustments\nCommunicate progress clearly and sensitively to parents at regular review meetings\nContribute to staff professional development on dyslexia identification and classroom accommodations\nKeep accurate records and write detailed termly progress reports',
    requirements: 'B.Ed. in Special Needs Education, or B.Sc. in Psychology/Education with a postgraduate qualification in Special Education or Dyslexia\nValid TRCN registration\nRecognised dyslexia assessment and teaching qualification (BDA-accredited training, AMBDA, or equivalent)\n2–6 years of experience working with students with dyslexia or other SpLDs\nDeep knowledge of structured literacy approaches and multi-sensory teaching methods\nHigh level of patience, creativity, and genuine passion for supporting children with learning differences\nStrong report-writing and parent communication skills',
    perks: ['Health insurance', 'Annual performance bonus', 'Specialist professional development budget', 'TRCN renewal support', 'End-of-year bonus', 'Small class sizes and specialist team support', 'Deeply rewarding work in an inclusive school community'],
    applyInstructions: 'Send your CV, specialist dyslexia qualification, and a cover letter to jobs@steppingstones.edu.ng with subject: APPLICATION – Special Education Teacher (Dyslexia).',
  },
  {
    id:'v24', sId:'pac', sName:'Pacelli School for the Blind', sColor:'#6B3FA0',
    city:'Surulere, Lagos', state:'Lagos', dept:'Non-academic / Support', type:'Full-time',
    title:'Braille Instructor', deadline:'1 Sep 2026',
    summary:'Certified Braille instructor to teach Grade 1 and Grade 2 Braille reading and writing and assistive technology skills to visually impaired students at Nigeria\'s leading specialist school.',
    applyEmail:'staff@pacelli.edu.ng', trcnRequired: true,
    experienceLevel: 'Mid-level (2–5 years)', minQualification: 'Diploma / B.Ed.',
    salaryRange: '₦85k–₦120k/month', location: 'Surulere, Lagos',
    roleOverview: 'Pacelli School for the Blind has been at the forefront of visual impairment education in Nigeria for decades. We are seeking a skilled and passionate Braille Instructor to teach Grade 1 and Grade 2 Braille reading and writing to our visually impaired students. You will help unlock literacy, independence, and academic success for children who rely on Braille as their primary reading and writing medium. This role carries life-changing impact.',
    keyResponsibilities: 'Teach Grade 1 (uncontracted) and Grade 2 (contracted) Braille reading and writing across all age groups\nConduct initial assessments to determine each student\'s Braille proficiency level\nDesign and deliver progressive, structured Braille lessons aligned with the school\'s literacy curriculum\nAdapt standard learning materials into Braille using a Perkins Brailler, BrailleNote, or equivalent device\nMonitor and document each student\'s reading speed, accuracy, and comprehension\nTeach the use of assistive technology — screen readers, refreshable Braille displays, and audio learning aids\nCollaborate with subject teachers to ensure Braille access to all curriculum content\nCommunicate termly progress to parents and contribute to Individual Education Plans\nParticipate in school events and prepare students for national Braille competitions',
    requirements: 'Recognised Braille qualification from NCBH, RNIB, or an equivalent certifying body — required\nB.Ed. in Special Needs Education (visual impairment specialisation) is strongly preferred\nValid TRCN registration\n2–5 years of experience teaching Braille to visually impaired learners\nFluency in both Grade 1 and Grade 2 Unified English Braille (UEB)\nKnowledge of assistive technology for the visually impaired\nDeep empathy, patience, and commitment to the dignity and independence of visually impaired students',
    perks: ['Health insurance', 'Annual performance bonus', 'Specialist professional development budget', 'TRCN renewal support', 'End-of-year bonus', 'Accommodation support for relocating candidates', 'Profoundly rewarding work in a pioneering specialist school'],
    applyInstructions: 'Send your Braille certification, CV, and a cover letter to staff@pacelli.edu.ng with subject: APPLICATION – Braille Instructor.',
  },
];

export const V_DEPTS   = ['All departments','Secondary – Academic','Primary – Academic','Nursery – Academic','Administration','Non-academic / Support'];
export const V_TYPES   = ['All','Full-time','Part-time','Contract'];
export const V_TYPE_CLR: Record<string,string> = { 'Full-time':'#1F8A5B','Part-time':'#2A6FDB','Contract':'#D97706' };
export const V_SPEC_IDS = ['pac','sfd','sts'];

